# src/aloegraph/V2/v2_base_response.py
"""
v2_base_response
================

- **Module:** `src/aloegraph/V2/v2_base_response.py`
- **GitHub:** <https://github.com/aloecraft/AloeGraph>
- **Author:** AloeCraft.org (Michael Godfrey)

Defines the abstract base response model for AloeGraph V2 agents.

This module provides `BaseResponse`, a Pydantic + ABC hybrid class that
establishes the common schema for agent responses. It ensures consistent
validation of response fields while requiring subclasses to implement
a standardized system instruction method.

Overview
--------
- **BaseResponse**:
  Abstract class combining Pydantic's data validation with an abstract
  interface for agent system prompts. All agent response types in AloeGraph
  should inherit from this base to guarantee a consistent contract.

Attributes
----------
- `success` : bool
    Indicates whether the operation succeeded.
- `agent_message` : str
    Message intended for the user, generated by the agent.
- `error_message` : str
    Error details if the operation failed.

Abstract Methods
----------------
- `SYSTEM_INSTRUCTION(agent_name, agent_description)`:
    Must be implemented by subclasses to return the system prompt string
    that guides agent behavior. This enforces a consistent interface for
    constructing agent instructions across different response types.

Usage
-----
Subclass `BaseResponse` to define specific agent response schemas and
system instructions:

```python
class ChatAgentResponse(BaseResponse):
    @classmethod
    def SYSTEM_INSTRUCTION(cls, agent_name: str, agent_description: str) -> str:
        return f"{agent_name}: {agent_description}"
```
"""

from abc import ABC, abstractmethod
from pydantic import BaseModel, Field

class BaseResponse(BaseModel, ABC):
    """
    Abstract base class for agent responses.

    This class defines the common schema for responses returned by chat agents
    in the AloeGraph framework. It combines Pydantic's validation and field
    descriptions with an abstract interface for generating system instructions.

    Attributes
    ----------
    success : bool
        Flag indicating whether the operation succeeded. Defaults to False.
    agent_message : str
        The message intended for the user, typically generated by the agent.
    error_message : str
        Error details if the operation failed. Empty string if no error occurred.
    """
    success: bool = Field(
        default=False, description="True if operation succeeded")
    agent_message: str = Field(
        default="", description="Message to show to user")
    error_message: str = Field(default="", description="Error details if any")

    @classmethod
    @abstractmethod
    def SYSTEM_INSTRUCTION(cls, agent_name: str, agent_description: str) -> str:
        """
        Construct the system prompt for this agent type.

        This method must be implemented by subclasses to provide the
        instruction text that guides the agent's behavior. The instruction
        typically encodes the agent's role, purpose, or constraints.

        Parameters
        ----------
        agent_name : str
            The name of the agent (used for identification in prompts).
        agent_description : str
            A human-readable description of the agent's purpose or role.

        Returns
        -------
        str
            The system instruction string to be used in prompt construction.
        """
        raise NotImplementedError
