# src/aloegraph/V2/v2_base_model.py
"""
v2_base_model
=============

- **Module:** `src/aloegraph/V2/v2_base_model.py`
- **GitHub:** <https://github.com/aloecraft/AloeGraph>
- **Author:** AloeCraft.org (Michael Godfrey)

Core data models and abstract interfaces for AloeGraph V2.

This module defines the foundational Pydantic models, enums, and abstract
base classes used throughout AloeGraph. These components provide the
schema, metadata, and notification interfaces that support graph execution,
visualization, and chat interaction.

Overview
--------
- **V2AloeConfig**:
  Configuration state object for `V2AloeGraph`. Tracks user/agent messages,
  error details, and control flags (`__EDGE__`, `__INTERRUPT__`, etc.) used
  during graph traversal.

- **NodeRenderShape**:
  Enumeration of Mermaid diagram shapes for rendering nodes in flowcharts
  and state diagrams.

- **AloeNodeData**:
  Metadata model for graph nodes, including name, description, entry status,
  initialization flag, and render shape.

- **AloeEdgeData**:
  Metadata model for graph edges, including target node, label, description,
  and interrupt flag.

- **ChatMessage**:
  Schema for individual chat messages exchanged between user and agent,
  including sequence ID, role, content, timestamp, and optional error info.

- **LogNotifier (abstract)**:
  Interface for logging systems that record or clear log messages. Provides
  a contract for implementations that direct logs to console, files, or UI.

- **ChatNotifier (abstract)**:
  Extends `LogNotifier` with methods for managing chat state and user-facing
  messages. Defines hooks for attaching agents, adding replies, clearing
  messages, and updating status indicators.

- **ChatAgent (abstract)**:
  Interface for chat agents that process user messages and interact with
  dialogs. Defines the `notify` method for handling input and producing
  replies, plus a deprecated `set_dialog` hook.

Usage
-----
These models and interfaces form the backbone of AloeGraph V2. They are
referenced by higher‑level graph classes (`V2AloeGraph`, `V2AloeNodeGraph`)
and agent implementations to ensure consistent state management, schema
validation, and communication patterns.

Example
-------
```python
config = V2AloeConfig(user_message="Hello")
node_data = AloeNodeData(name="Start", is_entry=True)
edge_data = AloeEdgeData(target="End", description="finish")

msg = ChatMessage(sequence_id=1, role="user", content="Hi there", timestamp="2025-11-12T23:06:00Z")
```
"""

from abc import ABC, abstractmethod
from pydantic import BaseModel
from typing import Optional
from enum import StrEnum
from deprecated import deprecated

END = "__END__"

class V2AloeConfig(BaseModel):
    """
    Configuration state object for `V2AloeGraph`.

    This model captures the transient state of a graph execution, including
    user and agent messages, error information, and control flags used to
    manage graph traversal.

    Attributes
    ----------
    user_message : str, optional
        The most recent message provided by the user.
    agent_message : str, optional
        The most recent message generated by the agent.
    error_message : str, optional
        Error details if the agent or graph encountered a failure.
    __EDGE__ : str, optional
        Identifier for the current edge being traversed.
    __CONTINUE__ : str, optional
        Control flag indicating continuation of graph execution.
    __INTERRUPT__ : str, optional
        Control flag indicating interruption of graph execution.
    __RESUME__ : str, optional
        Control flag indicating resumption of graph execution.
    """
    user_message: str = None
    agent_message: str = None
    error_message: str = None
    __EDGE__: str = None
    __CONTINUE__: str = None
    __INTERRUPT__: str = None
    __RESUME__: str = None

    def _enter(self):
        """
        Reset agent and error messages when entering a new state.
        """
        self.agent_message = ""
        self.error_message = ""
        __EDGE__: str = None

    def _exit(self):
        """
        Clear the user message when exiting the current state.
        """
        self.user_message = ""


class NodeRenderShape(StrEnum):
    """
    Enumeration of node render shapes for Mermaid diagrams.

    Used with `AloeNode` to control how nodes are displayed in generated
    flowcharts or state diagrams.
    """
    SQUARE = "[{}]"
    ROUND = "({})"
    STADIUM = "([{}])"
    SUBROUTINE = "[[{}]]"
    CYLINDER = "[({})]"
    CIRCLE = "(({}))"
    ASYM = ">{}]"
    DIAMOND = "{{{}}}"
    HEXAGON = "{{{{{}}}}}"
    PARALLEL = "[\\{}\\]"
    TRAP = "[/{}\\]"
    TRAP_ALT = "[\\{}/]"
    DBL_CIRCLE = "((({})))"


class AloeNodeData(BaseModel):
    """
    Metadata for an `AloeNode`.

    Defines the properties of a node in the AloeGraph, including its name,
    description, entry status, initialization state, and render shape.

    Attributes
    ----------
    name : str, optional
        The identifier or label for the node.
    description : str, optional
        Human-readable description of the node's purpose.
    is_entry : bool
        Whether this node is the entry point of the graph. Defaults to False.
    _is_initialized : bool
        Internal flag indicating whether the node has been initialized.
    node_render_shape : NodeRenderShape
        The visual shape used when rendering the node in diagrams.
    """

    name: str = None
    description: Optional[str] = None
    is_entry: bool = False
    _is_initialized: bool = False
    node_render_shape: NodeRenderShape = NodeRenderShape.SQUARE


class AloeEdgeData(BaseModel):
    """
    Metadata for an `AloeEdge`.

    Defines the properties of an edge connecting nodes in the AloeGraph,
    including its target, label, description, and whether it represents
    an interrupt.

    Attributes
    ----------
    target : str
        The identifier of the target node this edge connects to.
    name : str, optional
        The label or name of the edge.
    description : str, optional
        Human-readable description of the edge's purpose.
    interrupt : bool
        Whether this edge represents an interrupt in the graph flow.
    """
    target: str
    name: str = None
    description: Optional[str] = None
    interrupt: bool = False


class ChatMessage(BaseModel):
    """
    Representation of a single chat message.

    Used by `ChatAgent` in `v2_chat_model.ChatAgentState` to capture
    conversational exchanges between user and agent.

    Attributes
    ----------
    sequence_id : int
        Sequential identifier for the message in the conversation.
    role : str
        The role of the message sender (e.g., "user", "agent").
    content : str
        The textual content of the message.
    timestamp : str
        Timestamp of when the message was created.
    error_message : str, optional
        Error details if the message could not be processed correctly.
    """
    sequence_id: int = -1
    role: str
    content: str
    timestamp: str
    error_message: Optional[str] = None


class LogNotifier(ABC):
    """
    Abstract base class for logging notifications.

    Provides an interface for components that need to record or clear log messages.
    Implementations may direct logs to console, files, UI widgets, or other sinks.
    """

    @abstractmethod
    def add_log(self, text: str) -> None:
        """
        Add a log entry.

        Parameters
        ----------
        text : str
            The log message to record.
        """
        print(f"   LOG > {text}")

    @abstractmethod
    def clear_log(self) -> None:
        """
        Clear all log entries.
        """
        pass


class ChatNotifier(LogNotifier):
    """
    Abstract base class for chat notification.

    Extends LogNotifier with methods for managing chat state and user-facing messages.
    Implementations may update a UI, send events, or integrate with external systems.
    """

    @abstractmethod
    def set_agent(self, agent: "ChatAgent") -> "ChatAgent":
        """
        Attach a chat agent to this notifier.

        Parameters
        ----------
        agent : ChatAgent
            The agent responsible for handling user input and producing replies.

        Returns
        -------
        ChatAgent
            The agent that was set.
        """
        pass

    @abstractmethod
    def add_reply(self, text: str, sender: str = None) -> None:
        """
        Add a reply message to the chat output.

        Parameters
        ----------
        text : str
            The reply text.
        sender : str, optional
            Label for the sender (e.g., "Agent" or "User").
        """
        pass

    @abstractmethod
    def clear_msgs(self) -> None:
        """
        Clear all chat messages from the output.
        """
        pass

    @abstractmethod
    def set_status(self, text: str) -> None:
        """
        Update the chat status indicator.

        Parameters
        ----------
        text : str
            Status message to display (e.g., "ready", "waiting").
        """
        pass


class ChatAgent(ABC):
    """
    Abstract base class for chat agents.

    Defines the interface for agents that process user messages and interact with dialogs.
    """
    @abstractmethod
    def notify(self, msg: str) -> str:
        """
        Handle a new user message asynchronously.

        Parameters
        ----------
        msg : str
            The user message to process.

        Returns
        -------
        str
            The agent's reply message.
        """
        pass

    @abstractmethod
    @deprecated
    def set_dialog(self, dialog: "ChatDialog") -> None:
        pass
