# src/aloegraph/agent/simple_gemini_agent.py
"""
simple_gemini_agent
===================

- **Module:** `src/aloegraph/agent/simple_gemini_agent.py`
- **GitHub:** <https://github.com/aloecraft/AloeGraph>
- **Author:** AloeCraft.org (Michael Godfrey)

Defines a simple chat agent implementation for AloeGraph V2 that integrates
with Google's Gemini API. This module provides both the response schema and
the agent logic for handling single‑turn conversations in a notebook or
application environment.

Overview
--------
- **GeminiChatAgentResponse**:
  A `BaseResponse` subclass defining the schema for agent replies. Includes
  the `agent_message` field and a `SYSTEM_INSTRUCTION` classmethod that
  guides the Gemini model to produce structured JSON output conforming to
  the schema.

- **GeminiChatAgent**:
  A concrete implementation of `ChatAgent` that:
    * Uses `GeminiJSONResponseGenerator` to send prompts to the Gemini API.
    * Validates responses against the `GeminiChatAgentResponse` schema.
    * Forwards agent replies to a `ChatNotifier` for display.
    * Provides a `factory` method for convenient instantiation and dialog
      attachment.

Responsibilities
----------------
- Encapsulate Gemini API calls for generating conversational replies.
- Enforce schema validation to ensure predictable agent outputs.
- Integrate with AloeGraph’s notifier system for displaying messages and
  managing chat state.
- Provide a lightweight, single‑turn example agent suitable for testing
  Gemini connectivity.

Usage
-----
Instantiate a `GeminiChatAgent` with a Gemini client and a chat notifier:

```python
from aloegraph.agent.simple_gemini_agent import GeminiChatAgent
from aloegraph.dialog.notebook_chat_dialog import NotebookChatDialog
from google import genai

client = genai.Client(api_key=GEMINI_API_KEY)
dialog = NotebookChatDialog()
agent = GeminiChatAgent.factory(client, dialog)

agent.notify("Hello!")  # sends message to Gemini and displays reply
```
"""

import aloegraph.V2.v2_base_model as v2_base_model
import aloegraph.V2.v2_base_response as v2_base_response
from aloegraph.V2.response_generator import GeminiJSONResponseGenerator as Gemini

import deprecated
import json
from typing import Any, Dict
from pydantic import Field
from google import genai


class GeminiChatAgentResponse(v2_base_response.BaseResponse):
    """
    Schema for responses generated by GeminiChatAgent.

    Attributes
    ----------
    agent_message : str
        The text message produced by the agent in response to user input.
    """
    agent_message: str = Field(
        default_factory=str, description="Response to be shown to user")

    @classmethod
    def SYSTEM_INSTRUCTION(cls, agent_name: str, agent_description: str):
        return f"""
You are a friendly AI Chat Agent for {agent_name}.

**What is {agent_name}?**

> {agent_description}

**What To Know:**
- Your task is to return a response to continue the conversation

**Output Description**
- Always return a JSON object with exactly this schema:
  {json.dumps(cls.model_json_schema(), indent=4)}
"""


class GeminiChatAgent(v2_base_model.ChatAgent):
    """
    A chat agent that uses Google's Gemini API to generate responses.

    This agent implements the `ChatAgent` interface from `v2_base_model` and
    integrates with a `ChatNotifier` to display replies. It sends user messages
    to the Gemini model, validates the output against a Pydantic schema, and
    forwards the agent's message to the notifier.

    Parameters
    ----------
    client : genai.Client
        The Google Gemini client used to send requests to the model.
    dialog : v2_base_model.ChatNotifier
        The notifier responsible for displaying agent replies and managing chat state.
    """

    def __init__(self, client: genai.Client, dialog: v2_base_model.ChatNotifier):
        """
        Initialize a GeminiChatAgent with a Gemini client and a chat notifier.

        Parameters
        ----------
        client : genai.Client
            The Gemini client instance.
        dialog : ChatNotifier
            The notifier that will display replies and manage chat state.
        """
        self.response_generator = Gemini[GeminiChatAgentResponse](
            client, agent_name="Simple AloeCraft Chat Agent", agent_description="Useful for testing connection to Gemini. This example is single message, single response. No chat history is retained. You can download from [GitHub](https://github.com/aloecraft/AloeGraph) and run locally or run in Google Colab")
        self.dialog = dialog
        self.system_instruction = "You are a helpful assistant"

    def notify(self, msg: str) -> str:
        """
        Handle a new user message by sending it to the Gemini model.

        Parameters
        ----------
        msg : str
            The user message to process.

        Returns
        -------
        str
            The agent's reply message.
        """
        gemini_reply: GeminiChatAgentResponse = self.response_generator.generate(
            msg)

        if self.dialog:
            self.dialog.add_reply(f"{gemini_reply.agent_message}", "agent")

    @deprecated.deprecated
    def set_dialog(self, dialog: "ChatDialog") -> None:
        """
        Attach a dialog to the agent.

        Notes
        -----
        This method is not implemented. Use `v2_base_model.ChatNotifier` instead.
        """
        raise NotImplementedError("Use v2_base_model.ChatNotifier instead")

    @classmethod
    def factory(cls, client: genai.Client, dialog: v2_base_model.ChatNotifier) -> "GeminiChatAgent":
        """
        Convenience factory for creating a GeminiChatAgent and attaching it to a dialog.

        Parameters
        ----------
        client : genai.Client
            The Gemini client instance.
        dialog : ChatNotifier
            The notifier that will display replies and manage chat state.

        Returns
        -------
        GeminiChatAgent
            A new agent instance attached to the provided dialog.

        Examples
        --------
        >>> from aloegraph.agent.simple_gemini_chat_agent import GeminiChatAgent
        >>> from aloegraph.dialog.notebook_chat_dialog import NotebookChatDialog
        >>> from google import genai
        >>> client = genai.Client(api_key=GEMINI_API_KEY)
        >>> notebook_dialog = NotebookChatDialog()
        >>> agent = GeminiChatAgent.factory(client, notebook_dialog)
        """
        agent = cls(client, dialog)
        dialog.set_agent(agent)
        return agent
